dist: xenial   # required for Python >= 3.7

language: python

cache:
  pip: true
  apt: true
  directories:
  - $HOME/.cache/traffic/

python:
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - TRAFFIC_NOPLUGIN=""

addons:
  apt:
    packages:
      # Shapely
      - libgeos-dev
      # Cartopy
      - libproj-dev
      - proj-bin
      - proj-data
      - libarchive-dev

before_install:
  - python -m pip install -U pip
  - python -m pip --version

install:
  # possible bug with pytest 4.6.0
  - python -m pip install --upgrade codecov pytest-cov pytest==4.5
  - python -m pip install --upgrade numpy pyproj  # dependency for cartopy
  - python -m pip install --upgrade libarchive  # dependency for so6.7z
  - python -m pip install --upgrade xarray
  - python -m pip install --upgrade sphinx sphinx-rtd-theme
  - python -m pip install -e .

script:
  - travis_wait 30 python -m pytest --cov --cov-report term-missing

after_success:
  - codecov
  - cd docs; make html; cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: traffic-viz/traffic-viz.github.io
  target_branch: master
  local_dir: docs/_build/html
  on:
    condition: $TRAVIS_PYTHON_VERSION = 3.7
