sync:
  uv sync --all-packages --frozen
  pnpm install --frozen-lockfile

fmt:
  uv run --all-packages ruff check tangram_* --fix
  uv run --all-packages ruff format tangram_*
  pnpm fmt
  pnpm lint:fix

check:
  uv run --all-packages ruff check tangram_*
  uv run --all-packages ruff format tangram_* --check
  uv run --all-packages mypy tangram_landing/src
  pnpm check
