name: docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # jupyter Docker image for users
      - name: Build jupyter docker image
        run: docker build --file docker/jupyter.Dockerfile --tag ghcr.io/xoolive/traffic/jupyter:${{ inputs.tag }} --tag ghcr.io/xoolive/traffic/jupyter:latest docker

      - name: Test jupyter image
        run: docker run ghcr.io/xoolive/traffic/jupyter:latest python -c "import traffic; print(traffic.__version__)"
        
      - name: Push jupyter docker image
        run: docker push ghcr.io/xoolive/traffic/jupyter:latest

      # dev Docker image
      - name: Build dev docker image
        run: docker build --file docker/poetry.Dockerfile --tag ghcr.io/xoolive/traffic/dev:${{ inputs.tag }} --tag ghcr.io/xoolive/traffic/dev:latest .

      - name: Test dev docker image
        run: docker run ghcr.io/xoolive/traffic/dev:latest /bin/bash -c "pip install -e .; python -c \"import traffic; print(traffic.__version__)\""
        
      - name: Push dev image
        run: docker push ghcr.io/xoolive/traffic/dev:latest
