name: docker

on:
  workflow_dispatch:
  push:
  # the simple "push" should change to 
  # push:
  #   branches:
  #     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build --file docker/jupyter.Dockerfile --tag ghcr.io/traffic/jupyter:latest docker

      - name: Import the library
        run: docker run ghcr.io/traffic/jupyter:latest -c "import traffic; print(traffic.__version__)"
        
      - name: Push image
        run: docker push ghcr.io/traffic/jupyter:latest
